Update jira_issue_key_finder2.yml

diff --git a/.github/workflows/jira_issue_key_finder2.yml b/.github/workflows/jira_issue_key_finder2.yml
--- a/.github/workflows/jira_issue_key_finder2.yml
+++ b/.github/workflows/jira_issue_key_finder2.yml
@@ -29,7 +29,7 @@ jobs:
 
     - name: should skip if working, or else error out
       if: ${{ steps.find.outputs.issue == '' }}
-      run: echo "Issue not found" && exit 1
+      run: echo "Issue not found" && exit 12
 
     - name: Find issue info
       run: echo "Issue ${{ steps.find.outputs.issue }} was found"
